# Question 2 - Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

from functools import reduce

def fibonacci_generator(end):
    f1, f2 = 0, 1
    while f1 < end:
        yield f1
        f1, f2 = f2, f1 + f2

def sum_if_even(accumulator, value):
    return accumulator + value if value % 2 == 0 else accumulator

def main():
    return reduce(sum_if_even, fibonacci_generator(4_000_000))

if __name__ == "__main__":
    print(main())